-- Create emails table
CREATE TABLE IF NOT EXISTS public.emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    "from" TEXT,
    "to" TEXT,
    subject TEXT,
    body TEXT,
    date TIMESTAMPTZ,
    message_id TEXT UNIQUE,
    in_reply_to TEXT,
    email_references TEXT,
    folder TEXT DEFAULT 'inbox',
    is_read BOOLEAN DEFAULT FALSE,
    owner_id UUID REFERENCES auth.users(id),
    snippet TEXT
);

-- Initialize Row Level Security (RLS)
ALTER TABLE public.emails ENABLE ROW LEVEL SECURITY;

-- Create Policy to allow users to see their own emails (or all if open system)
-- For now, allowing all for authenticated users to avoid permission issues during dev
CREATE POLICY "Allow all operations for authenticated users" ON public.emails
    FOR ALL
    USING (auth.role() = 'authenticated')
    WITH CHECK (auth.role() = 'authenticated');

-- Grant access to service role (optional but good practice)
GRANT ALL ON public.emails TO service_role;
