-- Create table for storing agent payment details
CREATE TABLE IF NOT EXISTS public.agent_payment_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id BIGINT REFERENCES public.agents(id) ON DELETE CASCADE NOT NULL UNIQUE,
  account_holder_name TEXT,
  bank_name TEXT,
  account_number TEXT,
  ifsc_code TEXT,
  upi_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Disable Row Level Security (RLS)
-- Since the application uses a custom session cookie for Agents (not Supabase Auth UUIDs referencing this table),
-- RLS using auth.uid() matches typically fail or cause type mismatches (UUID vs BIGINT).
-- We will rely on the API route to Authenticate and Authorize the request.
ALTER TABLE public.agent_payment_details DISABLE ROW LEVEL SECURITY;

-- If you previously enabled it, this ensures it is off.
-- If you absolutely need RLS, you would need a way to map auth.uid() to agent_id within Postgres,
-- which usually requires a lookup table or a column in agents table storing the auth_id.

-- Drop any existing policies that might cause errors
DROP POLICY IF EXISTS "Agents can view their own payment details" ON public.agent_payment_details;
DROP POLICY IF EXISTS "Agents can insert their own payment details" ON public.agent_payment_details;
DROP POLICY IF EXISTS "Agents can update their own payment details" ON public.agent_payment_details;

-- Grant access to service_role and authenticated/anon (since RLS is off, API handles security)
GRANT ALL ON TABLE public.agent_payment_details TO service_role;
GRANT ALL ON TABLE public.agent_payment_details TO anon;
GRANT ALL ON TABLE public.agent_payment_details TO authenticated;
