ALTER TABLE public.product_quotations
ADD COLUMN IF NOT EXISTS payment_status TEXT, 
ADD COLUMN IF NOT EXISTS received_amount NUMERIC,
ADD COLUMN IF NOT EXISTS transaction_id TEXT,
ADD COLUMN IF NOT EXISTS payment_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS payment_notes TEXT,
ADD COLUMN IF NOT EXISTS dispatch_reference TEXT,
ADD COLUMN IF NOT EXISTS dispatch_notes TEXT,
ADD COLUMN IF NOT EXISTS billed_reference TEXT,
ADD COLUMN IF NOT EXISTS billed_notes TEXT,
ADD COLUMN IF NOT EXISTS discount_type TEXT DEFAULT 'All',
ADD COLUMN IF NOT EXISTS discount_value NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS validity_days INTEGER DEFAULT 30;
